---
version: '2'
services:
  web:
    image: 'debian:jessie'
    command: sleep infinity
    hostname: debianhost
    environment:
      TERM: xterm

  postgres:
    container_name: "postgres-container-db"
    image: "postgres:9.6.1"
    ports:
     - "5433:5432"
    volumes:
     - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      TERM: xterm

  uaa:
    container_name: "uaa-container-server"
    image: "hortonworks/cloudbreak-uaa:2.7.1"
    ports:
     - "7070:8080"
    environment:
      DB_PORT_5432_TCP_ADDR: "postgres-container-db"
      DB_PORT_5432_TCP_PORT: "5432"
      DB_ENV_DB: "postgres"
      DB_ENV_PASS: "mysecretpassword"
      
