---
version: '2'
services:
  web:
    image: 'debian:jessie'
    command: sleep infinity
    hostname: debianhost
    environment:
      TERM: xterm

  postgres:
    container_name: "postgres-container-db"
    image: "postgres:9.6.1"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      TERM: xterm
