server:
    port: 8480
 

spring:
   profiles:
      active: development

   application.name: iprofile-asset-manager
---
spring:
  profiles: development

  jpa:
    database: MYSQL

  datasource:
    url: jdbc:mysql://localhost/asset
    username: root
    password: pacific2K9!

security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt.keyUri: http://localhost:8080/uaa/token_key
      userInfoUri: http://localhost:8080/uaa/userinfo
        